import fs from 'node:fs';
import path from 'node:path';

export type WrapperRuntime = 'native' | 'node';

export const writeWrapper = (
  wrapperPath: string,
  configDir: string,
  binaryPath: string,
  runtime: WrapperRuntime = 'node'
) => {
  const tweakDir = path.join(path.dirname(configDir), 'tweakcc');
  const runLine = runtime === 'node' ? `node "${binaryPath}" "$@"` : `"${binaryPath}" "$@"`;
  const execLine = runtime === 'node' ? `exec node "${binaryPath}" "$@"` : `exec "${binaryPath}" "$@"`;
  const envLoader = [
    'if command -v node >/dev/null 2>&1; then',
    '  __cc_mirror_env_file="$(mktemp)"',
    '  node - <<\'NODE\' > "$__cc_mirror_env_file" || true',
    "const fs = require('fs');",
    "const path = require('path');",
    'const dir = process.env.CLAUDE_CONFIG_DIR;',
    'if (!dir) process.exit(0);',
    "const file = path.join(dir, 'settings.json');",
    'const escape = (value) => "\'" + String(value).replace(/\'/g, "\'\\"\'\\"\'") + "\'";',
    'try {',
    '  if (fs.existsSync(file)) {',
    "    const data = JSON.parse(fs.readFileSync(file, 'utf8'));",
    "    const env = data && typeof data === 'object' ? data.env : null;",
    "    if (env && typeof env === 'object') {",
    '      for (const [key, value] of Object.entries(env)) {',
    '        if (!key) continue;',
    '        process.stdout.write(`export ${key}=${escape(value)}\\n`);',
    '      }',
    '    }',
    '  }',
    '} catch {',
    '  // ignore malformed settings',
    '}',
    'NODE',
    '  if [[ -s "$__cc_mirror_env_file" ]]; then',
    '    # shellcheck disable=SC1090',
    '    source "$__cc_mirror_env_file"',
    '  fi',
    '  rm -f "$__cc_mirror_env_file" || true',
    'fi',
  ];

  const authGuards = [
    'if [[ "${CC_MIRROR_UNSET_AUTH_TOKEN:-0}" != "0" ]]; then',
    '  unset ANTHROPIC_AUTH_TOKEN',
    'fi',
    'if [[ "${CC_MIRROR_OAUTH_ONLY:-0}" != "0" ]]; then',
    '  unset ANTHROPIC_API_KEY',
    '  unset ANTHROPIC_AUTH_TOKEN',
    'fi',
    'if [[ "${CC_MIRROR_UNSET_PROXY_KEYS:-0}" != "0" ]]; then',
    '  unset MINIMAX_API_KEY',
    '  unset Z_AI_API_KEY',
    'fi',
  ];

  const gateway = [
    'if [[ "${CC_MIRROR_LLM_GATEWAY:-0}" != "0" ]]; then',
    '  __cc_mirror_gateway_script="${CLAUDE_CONFIG_DIR}/llm-gateway.mjs"',
    '  if [[ ! -f "$__cc_mirror_gateway_script" ]]; then',
    '    echo "cc-mirror: missing gateway script: $__cc_mirror_gateway_script" >&2',
    '    exit 1',
    '  fi',
    '  __cc_mirror_gateway_ready="$(mktemp)"',
    '  __cc_mirror_gateway_log="${CLAUDE_CONFIG_DIR}/llm-gateway.log"',
    '  __cc_mirror_gateway_prefix="$(node -e "process.stdout.write(require(\'crypto\').randomBytes(12).toString(\'hex\'))")"',
    '  __cc_mirror_gateway_env=(env)',
    '  for __cc_mirror_var in HTTP_PROXY HTTPS_PROXY ALL_PROXY http_proxy https_proxy all_proxy npm_config_http_proxy npm_config_https_proxy npm_config_proxy NPM_CONFIG_HTTP_PROXY NPM_CONFIG_HTTPS_PROXY NPM_CONFIG_PROXY GLOBAL_AGENT_HTTP_PROXY GLOBAL_AGENT_HTTPS_PROXY; do',
    '    __cc_mirror_val="${!__cc_mirror_var:-}"',
    '    if [[ "$__cc_mirror_val" == *"127.0.0.1"* || "$__cc_mirror_val" == *"localhost"* ]]; then',
    '      __cc_mirror_gateway_env+=(-u "$__cc_mirror_var")',
    '    fi',
    '  done',
    '  __cc_mirror_gateway_env+=(-u NODE_OPTIONS)',
    '  "${__cc_mirror_gateway_env[@]}" node "$__cc_mirror_gateway_script" --config-dir "$CLAUDE_CONFIG_DIR" --ready-file "$__cc_mirror_gateway_ready" --prefix "$__cc_mirror_gateway_prefix" --port 0 >>"$__cc_mirror_gateway_log" 2>&1 &',
    '  __cc_mirror_gateway_pid="$!"',
    '  __cc_mirror_gateway_deadline=$((SECONDS+5))',
    '  while [[ ! -s "$__cc_mirror_gateway_ready" ]]; do',
    '    if [[ $SECONDS -ge $__cc_mirror_gateway_deadline ]]; then',
    '      break',
    '    fi',
    '    if ! kill -0 "$__cc_mirror_gateway_pid" 2>/dev/null; then',
    '      break',
    '    fi',
    '    sleep 0.05',
    '  done',
    '  if [[ ! -s "$__cc_mirror_gateway_ready" ]]; then',
    '    echo "cc-mirror: gateway failed to start; see $__cc_mirror_gateway_log" >&2',
    '    if [[ -n "${__cc_mirror_gateway_pid:-}" ]]; then',
    '      kill "$__cc_mirror_gateway_pid" 2>/dev/null || true',
    '      wait "$__cc_mirror_gateway_pid" 2>/dev/null || true',
    '    fi',
    '    rm -f "$__cc_mirror_gateway_ready" || true',
    '    exit 1',
    '  fi',
    '  source "$__cc_mirror_gateway_ready"',
    '  rm -f "$__cc_mirror_gateway_ready" || true',
    '  export CC_MIRROR_GATEWAY_PORT',
    '  export CC_MIRROR_GATEWAY_PREFIX',
    '  # Ensure localhost gateway traffic never goes through a proxy',
    '  __cc_mirror_no_proxy="${NO_PROXY:-}"',
    '  if [[ -z "$__cc_mirror_no_proxy" ]]; then',
    '    __cc_mirror_no_proxy="${no_proxy:-}"',
    '  fi',
    '  for __cc_mirror_host in 127.0.0.1 localhost; do',
    '    if [[ ",${__cc_mirror_no_proxy}," != *",${__cc_mirror_host},"* ]]; then',
    '      if [[ -n "$__cc_mirror_no_proxy" ]]; then',
    '        __cc_mirror_no_proxy="${__cc_mirror_no_proxy},${__cc_mirror_host}"',
    '      else',
    '        __cc_mirror_no_proxy="${__cc_mirror_host}"',
    '      fi',
    '    fi',
    '  done',
    '  export NO_PROXY="$__cc_mirror_no_proxy"',
    '  export no_proxy="$__cc_mirror_no_proxy"',
    '  export GLOBAL_AGENT_NO_PROXY="$__cc_mirror_no_proxy"',
    '  # Claude Code respects proxy env vars (incl npm_config_* and global-agent via NODE_OPTIONS).',
    '  # If these point at localhost and nothing is listening, requests fail like:',
    '  #   connect ECONNREFUSED 127.0.0.1:443',
    '  for __cc_mirror_var in HTTP_PROXY HTTPS_PROXY ALL_PROXY http_proxy https_proxy all_proxy npm_config_http_proxy npm_config_https_proxy npm_config_proxy NPM_CONFIG_HTTP_PROXY NPM_CONFIG_HTTPS_PROXY NPM_CONFIG_PROXY GLOBAL_AGENT_HTTP_PROXY GLOBAL_AGENT_HTTPS_PROXY; do',
    '    __cc_mirror_val="${!__cc_mirror_var:-}"',
    '    if [[ "$__cc_mirror_val" == *"127.0.0.1"* || "$__cc_mirror_val" == *"localhost"* ]]; then',
    '      unset "$__cc_mirror_var"',
    '    fi',
    '  done',
    '  if [[ "${NODE_OPTIONS:-}" == *"global-agent"* || "${NODE_OPTIONS:-}" == *"proxy"* ]]; then',
    '    unset NODE_OPTIONS',
    '  fi',
    '  __cc_mirror_gateway_mode="${CC_MIRROR_GATEWAY_MODE:-}"',
    '  if [[ -z "$__cc_mirror_gateway_mode" ]]; then',
    '    if [[ "${CC_MIRROR_OAUTH_ONLY:-0}" != "0" ]]; then',
    '      __cc_mirror_gateway_mode="fetch-hook"',
    '    else',
    '      __cc_mirror_gateway_mode="base-url"',
    '    fi',
    '  fi',
    '  export CC_MIRROR_GATEWAY_MODE="$__cc_mirror_gateway_mode"',
    '  if [[ "$__cc_mirror_gateway_mode" == "base-url" ]]; then',
    '    export ANTHROPIC_BASE_URL="http://127.0.0.1:${CC_MIRROR_GATEWAY_PORT}/${CC_MIRROR_GATEWAY_PREFIX}"',
    '  else',
    '    unset ANTHROPIC_BASE_URL',
    '    __cc_mirror_gateway_hook="${CLAUDE_CONFIG_DIR}/llm-gateway-hook.cjs"',
    '    if [[ ! -f "$__cc_mirror_gateway_hook" ]]; then',
    '      echo "cc-mirror: missing gateway hook: $__cc_mirror_gateway_hook" >&2',
    '      exit 1',
    '    fi',
    '  fi',
    '  __cc_mirror_cleanup_gateway() {',
    '    if [[ -n "${__cc_mirror_gateway_pid:-}" ]]; then',
    '      kill "$__cc_mirror_gateway_pid" 2>/dev/null || true',
    '      wait "$__cc_mirror_gateway_pid" 2>/dev/null || true',
    '    fi',
    '  }',
    '  trap __cc_mirror_cleanup_gateway EXIT INT TERM',
    'fi',
  ];
  // ANSI color codes for colored ASCII art
  const C = {
    reset: '\x1b[0m',
    // Zai: Gold/Amber gradient
    zaiPrimary: '\x1b[38;5;220m', // Gold
    zaiSecondary: '\x1b[38;5;214m', // Orange-gold
    zaiAccent: '\x1b[38;5;208m', // Dark orange
    zaiDim: '\x1b[38;5;172m', // Muted gold
    // MiniMax: Coral/Red/Orange gradient (from brand image)
    mmPrimary: '\x1b[38;5;203m', // Coral/salmon red
    mmSecondary: '\x1b[38;5;209m', // Light coral/orange
    mmAccent: '\x1b[38;5;208m', // Orange
    mmDim: '\x1b[38;5;167m', // Muted coral/dark red
    // OpenRouter: Cyan/Teal gradient
    orPrimary: '\x1b[38;5;43m', // Teal
    orSecondary: '\x1b[38;5;49m', // Bright teal
    orAccent: '\x1b[38;5;37m', // Deep cyan
    orDim: '\x1b[38;5;30m', // Muted teal
    // CCRouter: Sky blue gradient
    ccrPrimary: '\x1b[38;5;39m', // Sky blue
    ccrSecondary: '\x1b[38;5;45m', // Bright cyan
    ccrAccent: '\x1b[38;5;33m', // Deep blue
    ccrDim: '\x1b[38;5;31m', // Muted blue
    // Mirror: Silver/Chrome with electric blue
    mirPrimary: '\x1b[38;5;252m', // Silver/light gray
    mirSecondary: '\x1b[38;5;250m', // Platinum
    mirAccent: '\x1b[38;5;45m', // Electric cyan
    mirDim: '\x1b[38;5;243m', // Muted silver
    // Anthropax: Pink to orange gradient (MiniMax-inspired)
    arPrimary: '\x1b[38;5;198m', // Hot magenta
    arSecondary: '\x1b[38;5;205m', // Pink
    arAccent: '\x1b[38;5;209m', // Coral/orange
    arDim: '\x1b[38;5;167m', // Muted magenta
    // Default: White/Gray
    defPrimary: '\x1b[38;5;255m', // White
    defDim: '\x1b[38;5;245m', // Gray
  };

  const splash = [
    'if [[ "${CC_MIRROR_SPLASH:-0}" != "0" ]] && [[ -t 1 ]]; then',
    '  if [[ "$*" != *"--output-format"* ]]; then',
    '    __cc_label="${CC_MIRROR_PROVIDER_LABEL:-cc-mirror}"',
    '    __cc_style="${CC_MIRROR_SPLASH_STYLE:-default}"',
    '    __cc_show_label="1"',
    '    printf "\\n"',
    '    case "$__cc_style" in',
    '      zai)',
    "        cat <<'CCMZAI'",
    '',
    `${C.zaiPrimary}    ███████╗       █████╗ ██╗${C.reset}`,
    `${C.zaiPrimary}    ╚══███╔╝      ██╔══██╗██║${C.reset}`,
    `${C.zaiSecondary}      ███╔╝       ███████║██║${C.reset}`,
    `${C.zaiSecondary}     ███╔╝    ${C.zaiAccent}██╗${C.zaiSecondary} ██╔══██║██║${C.reset}`,
    `${C.zaiAccent}    ███████╗  ╚═╝ ██║  ██║██║${C.reset}`,
    `${C.zaiAccent}    ╚══════╝      ╚═╝  ╚═╝╚═╝${C.reset}`,
    '',
    `${C.zaiDim}    ━━━━━━━━━━${C.zaiPrimary}◆${C.zaiDim}━━━━━━━━━━${C.reset}`,
    `${C.zaiSecondary}      GLM Coding Plan${C.reset}`,
    '',
    'CCMZAI',
    '        __cc_show_label="0"',
    '        ;;',
    '      minimax)',
    "        cat <<'CCMMIN'",
    '',
    `${C.mmPrimary}    ███╗   ███╗██╗███╗   ██╗██╗███╗   ███╗ █████╗ ██╗  ██╗${C.reset}`,
    `${C.mmPrimary}    ████╗ ████║██║████╗  ██║██║████╗ ████║██╔══██╗╚██╗██╔╝${C.reset}`,
    `${C.mmSecondary}    ██╔████╔██║██║██╔██╗ ██║██║██╔████╔██║███████║ ╚███╔╝${C.reset}`,
    `${C.mmSecondary}    ██║╚██╔╝██║██║██║╚██╗██║██║██║╚██╔╝██║██╔══██║ ██╔██╗${C.reset}`,
    `${C.mmAccent}    ██║ ╚═╝ ██║██║██║ ╚████║██║██║ ╚═╝ ██║██║  ██║██╔╝ ██╗${C.reset}`,
    `${C.mmAccent}    ╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝╚═╝╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝${C.reset}`,
    '',
    `${C.mmDim}    ━━━━━━━━━━━━━━━━━━${C.mmPrimary}◆${C.mmDim}━━━━━━━━━━━━━━━━━━${C.reset}`,
    `${C.mmSecondary}           MiniMax-M2.1 ${C.mmDim}━${C.mmSecondary} AGI for All${C.reset}`,
    '',
    'CCMMIN',
    '        __cc_show_label="0"',
    '        ;;',
    '      openrouter)',
    "        cat <<'CCMORT'",
    '',
    `${C.orPrimary}     ██████╗ ██████╗ ███████╗███╗   ██╗${C.reset}`,
    `${C.orPrimary}    ██╔═══██╗██╔══██╗██╔════╝████╗  ██║${C.reset}`,
    `${C.orSecondary}    ██║   ██║██████╔╝█████╗  ██╔██╗ ██║${C.reset}`,
    `${C.orSecondary}    ██║   ██║██╔═══╝ ██╔══╝  ██║╚██╗██║${C.reset}`,
    `${C.orAccent}    ╚██████╔╝██║     ███████╗██║ ╚████║${C.reset}`,
    `${C.orAccent}     ╚═════╝ ╚═╝     ╚══════╝╚═╝  ╚═══╝${C.reset}`,
    `${C.orPrimary}    ██████╗  ██████╗ ██╗   ██╗████████╗███████╗██████╗${C.reset}`,
    `${C.orPrimary}    ██╔══██╗██╔═══██╗██║   ██║╚══██╔══╝██╔════╝██╔══██╗${C.reset}`,
    `${C.orSecondary}    ██████╔╝██║   ██║██║   ██║   ██║   █████╗  ██████╔╝${C.reset}`,
    `${C.orSecondary}    ██╔══██╗██║   ██║██║   ██║   ██║   ██╔══╝  ██╔══██╗${C.reset}`,
    `${C.orAccent}    ██║  ██║╚██████╔╝╚██████╔╝   ██║   ███████╗██║  ██║${C.reset}`,
    `${C.orAccent}    ╚═╝  ╚═╝ ╚═════╝  ╚═════╝    ╚═╝   ╚══════╝╚═╝  ╚═╝${C.reset}`,
    '',
    `${C.orDim}    ━━━━━━━━━━━━━${C.orPrimary}◆${C.orDim}━━━━━━━━━━━━━${C.reset}`,
    `${C.orSecondary}      One API ${C.orDim}━${C.orSecondary} Any Model${C.reset}`,
    '',
    'CCMORT',
    '        __cc_show_label="0"',
    '        ;;',
    '      ccrouter)',
    "        cat <<'CCMCCR'",
    '',
    `${C.ccrPrimary}     ██████╗ ██████╗██████╗  ██████╗ ██╗   ██╗████████╗███████╗██████╗${C.reset}`,
    `${C.ccrPrimary}    ██╔════╝██╔════╝██╔══██╗██╔═══██╗██║   ██║╚══██╔══╝██╔════╝██╔══██╗${C.reset}`,
    `${C.ccrSecondary}    ██║     ██║     ██████╔╝██║   ██║██║   ██║   ██║   █████╗  ██████╔╝${C.reset}`,
    `${C.ccrSecondary}    ██║     ██║     ██╔══██╗██║   ██║██║   ██║   ██║   ██╔══╝  ██╔══██╗${C.reset}`,
    `${C.ccrAccent}    ╚██████╗╚██████╗██║  ██║╚██████╔╝╚██████╔╝   ██║   ███████╗██║  ██║${C.reset}`,
    `${C.ccrAccent}     ╚═════╝ ╚═════╝╚═╝  ╚═╝ ╚═════╝  ╚═════╝    ╚═╝   ╚══════╝╚═╝  ╚═╝${C.reset}`,
    '',
    `${C.ccrDim}    ━━━━━━━━━━━━━━━━${C.ccrPrimary}◆${C.ccrDim}━━━━━━━━━━━━━━━━${C.reset}`,
    `${C.ccrSecondary}      Claude Code Router ${C.ccrDim}━${C.ccrSecondary} Any Model${C.reset}`,
    '',
    'CCMCCR',
    '        __cc_show_label="0"',
    '        ;;',
    '      mirror)',
    "        cat <<'CCMMIR'",
    '',
    `${C.mirPrimary}    ███╗   ███╗██╗██████╗ ██████╗  ██████╗ ██████╗${C.reset}`,
    `${C.mirPrimary}    ████╗ ████║██║██╔══██╗██╔══██╗██╔═══██╗██╔══██╗${C.reset}`,
    `${C.mirSecondary}    ██╔████╔██║██║██████╔╝██████╔╝██║   ██║██████╔╝${C.reset}`,
    `${C.mirSecondary}    ██║╚██╔╝██║██║██╔══██╗██╔══██╗██║   ██║██╔══██╗${C.reset}`,
    `${C.mirAccent}    ██║ ╚═╝ ██║██║██║  ██║██║  ██║╚██████╔╝██║  ██║${C.reset}`,
    `${C.mirAccent}    ╚═╝     ╚═╝╚═╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝${C.reset}`,
    '',
    `${C.mirDim}    ━━━━━━━━━━━━${C.mirAccent}◇${C.mirDim}━━━━━━━━━━━━${C.reset}`,
    `${C.mirSecondary}      Claude ${C.mirDim}━${C.mirSecondary} Pure Reflection${C.reset}`,
    '',
    'CCMMIR',
    '        __cc_show_label="0"',
    '        ;;',
    '      anthropic-router)',
    "        cat <<'CCMAR'",
    '',
    `${C.arPrimary}     █████╗  ███╗   ██╗ ████████╗ ██╗  ██╗ ██████╗   ██████╗ ██████╗   █████╗  ██╗  ██╗${C.reset}`,
    `${C.arPrimary}    ██╔══██╗ ████╗  ██║ ╚══██╔══╝ ██║  ██║ ██╔══██╗ ██╔═══██╗ ██╔══██╗ ██╔══██╗ ╚██╗██╔╝${C.reset}`,
    `${C.arSecondary}    ███████║ ██╔██╗ ██║    ██║    ███████║ ██████╔╝ ██║   ██║ ██████╔╝ ███████║  ╚███╔╝${C.reset}`,
    `${C.arSecondary}    ██╔══██║ ██║╚██╗██║    ██║    ██╔══██║ ██╔══██╗ ██║   ██║ ██╔═══╝  ██╔══██║  ██╔██╗${C.reset}`,
    `${C.arAccent}    ██║  ██║ ██║ ╚████║    ██║    ██║  ██║ ██║  ██║ ╚██████╔╝ ██║      ██║  ██║ ██╔╝ ██╗${C.reset}`,
    `${C.arAccent}    ╚═╝  ╚═╝ ╚═╝  ╚═══╝    ╚═╝    ╚═╝  ╚═╝ ╚═╝  ╚═╝  ╚═════╝ ╚═╝      ╚═╝  ╚═╝ ╚═╝  ╚═╝${C.reset}`,
    '',
    `${C.arDim}    ━━━━━━━━━━━━━━━━${C.arPrimary}◆${C.arDim}━━━━━━━━━━━━━━━━${C.reset}`,
    `${C.arSecondary}      Anthropax${C.arDim} · ${C.arSecondary}Anthropic main${C.arDim} + ${C.arSecondary}MiniMax subagents${C.reset}`,
    '',
    'CCMAR',
    '        __cc_show_label="0"',
    '        ;;',
    '      *)',
    "        cat <<'CCMGEN'",
    '',
    `${C.defPrimary}    ██████╗ ██████╗   ${C.defDim}━━  M I R R O R${C.reset}`,
    `${C.defPrimary}   ██╔════╝██╔════╝${C.reset}`,
    `${C.defPrimary}   ██║     ██║     ${C.defDim}Claude Code Variants${C.reset}`,
    `${C.defPrimary}   ██║     ██║     ${C.defDim}Custom Providers${C.reset}`,
    `${C.defPrimary}   ╚██████╗╚██████╗${C.reset}`,
    `${C.defPrimary}    ╚═════╝ ╚═════╝${C.reset}`,
    '',
    'CCMGEN',
    '        ;;',
    '    esac',
    '    if [[ "$__cc_show_label" == "1" ]]; then',
    '      printf "        %s\\n\\n" "$__cc_label"',
    '    else',
    '      printf "\\n"',
    '    fi',
    '  fi',
    'fi',
  ];
  const content = [
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    `export CLAUDE_CONFIG_DIR="${configDir}"`,
    `export TWEAKCC_CONFIG_DIR="${tweakDir}"`,
    ...envLoader,
    ...authGuards,
    '# Dynamic team name: purely directory-based, with optional TEAM modifier',
    '# Check for CLAUDE_CODE_TEAM_MODE (not TEAM_NAME) to avoid Claude Code overwriting',
    'if [[ -n "${CLAUDE_CODE_TEAM_MODE:-}" ]]; then',
    '  __cc_git_root=$(git rev-parse --show-toplevel 2>/dev/null || pwd)',
    '  __cc_folder_name=$(basename "$__cc_git_root")',
    '  if [[ -n "${TEAM:-}" ]]; then',
    '    # Folder name + TEAM modifier',
    '    export CLAUDE_CODE_TEAM_NAME="${__cc_folder_name}-${TEAM}"',
    '  else',
    '    # Just folder name (pure directory-based)',
    '    export CLAUDE_CODE_TEAM_NAME="${__cc_folder_name}"',
    '  fi',
    'elif [[ -n "${TEAM:-}" ]]; then',
    '  # TEAM env var set without team mode in settings - use folder + TEAM',
    '  __cc_git_root=$(git rev-parse --show-toplevel 2>/dev/null || pwd)',
    '  __cc_folder_name=$(basename "$__cc_git_root")',
    '  export CLAUDE_CODE_TEAM_NAME="${__cc_folder_name}-${TEAM}"',
    'fi',
    ...gateway,
    ...splash,
    'if [[ "${CC_MIRROR_LLM_GATEWAY:-0}" != "0" ]]; then',
    '  set +e',
    '  if [[ "${CC_MIRROR_GATEWAY_MODE:-}" == "fetch-hook" ]]; then',
    `    ${runtime === 'node' ? `node --require "$__cc_mirror_gateway_hook" "${binaryPath}" "$@"` : runLine}`,
    '  else',
    `    ${runLine}`,
    '  fi',
    '  __cc_exit=$?',
    '  set -e',
    '  exit $__cc_exit',
    'fi',
    execLine,
    '',
  ].join('\n');
  fs.writeFileSync(wrapperPath, content, { mode: 0o755 });
};
